# Generated by Django 5.2.7 on 2025-12-25 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='title',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensor'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
        migrations.CreateModel(
            name='IncidentAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('USER', 'User'), ('MANAGER', 'Manager'), ('SUPERVISOR', 'Supervisor')], max_length=20)),
                ('acknowledged', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(auto_now=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='api.measurement')),
            ],
            options={
                'unique_together': {('measurement', 'level')},
            },
        ),
    ]
